### ISSUE TITLE
Support abort signal in iterator.all()

### ISSUE THREAD

**Issue by ronag** [Level/classic-level#13]
Currently there is no good way to abort a `iterator.all()` call. Would be nice if the api could support `AbortController`.

**Comment by vweevers** [comment]
If your `all()` call is a long-running operation (getting many entries) it might not be the best method to use. For that same reason, `all()` currently uses `nextv()` under the hood, rather than a dedicated and optimized C++ method for `all()`. Because I assumed that the iterator typically just needs a few `nextv()` calls to get all entries. That does gives us a way to abort, in between `nextv()` calls, but I'm not sure that fits your use case.

Assuming that we did have such a dedicated method, let's say `iterator_all()` - how would we cancel the async work in C++?

**Comment by vweevers** [comment]
https://github.com/Level/abstract-level/pull/55

**Comment by vweevers** [comment]
Done in [2.0.0](https://github.com/Level/classic-level/releases/tag/v2.0.0).
